//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrowFee
    {
        public int BookBorrowFeeID { get; set; }
        public int NumberOfDateBorrowed { get; set; }
        public int BorrowFee { get; set; }
        public bool IsActive { get; set; }
    }
}
