//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetails
    {
        public BookDetails()
        {
            this.Books = new HashSet<Books>();
        }
    
        public int BookDetailsID { get; set; }
        public int AuthorID { get; set; }
        public string Barcode { get; set; }
        public byte CampusID { get; set; }
        public byte ResourceTypeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Campus Campus { get; set; }
        public virtual ResourceTypes ResourceTypes { get; set; }
        public virtual ICollection<Books> Books { get; set; }
    }
}
