//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBooksMaxNumber
    {
        public byte BorrowedBooksMaxNumberID { get; set; }
        public int maxNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
