//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        public Campus()
        {
            this.BookDetails = new HashSet<BookDetails>();
            this.User = new HashSet<User>();
        }
    
        public byte CampusID { get; set; }
        public string CampusName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BookDetails> BookDetails { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
